baseURL: https://www.covidshield.app/
languageCode: en
title: COVID Shield
publishDir: public
languages:
  en:
    title: COVID Shield
    languageName: English
    weight: 1
  fr:
    title: COVID Shield
    languageName: Français
    weight: 2
